/**
 * Reports — Generated Research Reports
 *
 * Phase 1: Professional placeholder layout.
 *
 * Phase 2+ Responsibilities:
 * - List and manage AI-generated research reports
 * - Reports generated by the Nitro Reports agent
 * - Markdown rendering with citation links
 * - Export to PDF, DOCX, LaTeX
 * - Share report via link (with access control)
 * - Version history and diff view
 *
 * @see docs/AGENTS.md — "Reports Agent" specification
 */

import { FileText } from 'lucide-react'
import { PagePlaceholder } from '@/components/ui/PagePlaceholder'

export function Reports() {
  return (
    <PagePlaceholder
      title="Reports"
      description="AI-generated research reports synthesizing papers, datasets, and cross-domain correlations."
      icon={<FileText className="w-5 h-5" />}
      phaseBadge="Phase 3"
      modules={[
        {
          label: 'Report List',
          description: 'Paginated list of reports with status (draft, generating, complete) and date.',
          phase: 'Phase 3',
        },
        {
          label: 'Report Viewer',
          description: 'Full Markdown rendering with interactive citation links and entity references.',
          phase: 'Phase 3',
        },
        {
          label: 'Export',
          description: 'Export reports to PDF, DOCX, LaTeX, or share via public link.',
          phase: 'Phase 3',
        },
        {
          label: 'Report Builder',
          description: 'Compose custom reports by selecting evidence, papers, and datasets.',
          phase: 'Phase 4',
        },
        {
          label: 'Version History',
          description: 'Track changes between report versions with a diff view.',
          phase: 'Phase 4',
        },
        {
          label: 'Collaboration',
          description: 'Share and collaborate on reports with team members.',
          phase: 'Phase 4',
        },
      ]}
    />
  )
}
